#!/bin/bash

# configure-xcode.sh
# Script to help configure xcconfig files in Xcode

echo "🔧 Xcode Configuration Helper"
echo "=============================="
echo ""
echo "To fix the crash when running standalone on your phone, you need to:"
echo ""
echo "1. 📁 Add xcconfig files to Xcode project:"
echo "   - Open MediaCloset.xcodeproj in Xcode"
echo "   - Drag 'Configs/Secrets.xcconfig' into the project navigator"
echo "   - Drag 'Configs/Local.secrets.xcconfig' into the project navigator"
echo "   - Make sure they're added to the project (not just referenced)"
echo ""
echo "2. ⚙️  Configure build settings:"
echo "   - Select the 'MediaCloset' project in the navigator"
echo "   - Go to the 'Info' tab"
echo "   - Under 'Configurations', you'll see Debug and Release"
echo "   - Set both Debug and Release to use 'Secrets.xcconfig'"
echo ""
echo "3. 🏗️  Build and run:"
echo "   - Clean build folder (⌘+Shift+K)"
echo "   - Build and run the project"
echo "   - The secrets will be automatically stored in iOS Keychain"
echo ""
echo "4. 📱 Test standalone:"
echo "   - Stop the app in Xcode"
echo "   - Launch the app directly from your phone"
echo "   - It should now work without crashing!"
echo ""
echo "💡 Alternative: If you can't configure xcconfig files right now,"
echo "   the app will use hardcoded fallback values to prevent crashes."
echo "   But for security, you should still set up the xcconfig files."
echo ""
echo "✅ The SecretsManager has been updated with fallback values"
echo "   so your app won't crash even without proper configuration."
