// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AlbumData struct {
	Artist   *string      `json:"artist,omitempty"`
	Album    *string      `json:"album,omitempty"`
	Year     *int         `json:"year,omitempty"`
	Label    *string      `json:"label,omitempty"`
	Genres   []string     `json:"genres,omitempty"`
	CoverURL *string      `json:"coverUrl,omitempty"`
	Tracks   []*TrackData `json:"tracks,omitempty"`
	Source   string       `json:"source"`
}

type Health struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Uptime  int    `json:"uptime"`
}

type MovieData struct {
	Title     string  `json:"title"`
	Director  *string `json:"director,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	PosterURL *string `json:"posterUrl,omitempty"`
	Plot      *string `json:"plot,omitempty"`
	Source    string  `json:"source"`
}

type Query struct {
}

type TrackData struct {
	Title           string `json:"title"`
	TrackNumber     *int   `json:"trackNumber,omitempty"`
	DurationSeconds *int   `json:"durationSeconds,omitempty"`
}
