// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Album struct {
	ID        string   `json:"id"`
	Artist    string   `json:"artist"`
	Album     string   `json:"album"`
	Year      *int     `json:"year,omitempty"`
	Label     *string  `json:"label,omitempty"`
	Genres    []string `json:"genres,omitempty"`
	CoverURL  *string  `json:"coverUrl,omitempty"`
	CreatedAt *string  `json:"createdAt,omitempty"`
	UpdatedAt *string  `json:"updatedAt,omitempty"`
}

type AlbumData struct {
	Artist   *string      `json:"artist,omitempty"`
	Album    *string      `json:"album,omitempty"`
	Year     *int         `json:"year,omitempty"`
	Label    *string      `json:"label,omitempty"`
	Genres   []string     `json:"genres,omitempty"`
	CoverURL *string      `json:"coverUrl,omitempty"`
	Tracks   []*TrackData `json:"tracks,omitempty"`
	Source   string       `json:"source"`
}

type Health struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Uptime  int    `json:"uptime"`
}

type Movie struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Director  *string `json:"director,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	CoverURL  *string `json:"coverUrl,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type MovieData struct {
	Title     string  `json:"title"`
	Director  *string `json:"director,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	PosterURL *string `json:"posterUrl,omitempty"`
	Plot      *string `json:"plot,omitempty"`
	Source    string  `json:"source"`
}

type Mutation struct {
}

type Query struct {
}

type SaveAlbumInput struct {
	Artist   string  `json:"artist"`
	Album    string  `json:"album"`
	Year     *int    `json:"year,omitempty"`
	Label    *string `json:"label,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type SaveAlbumResponse struct {
	Success bool        `json:"success"`
	ID      *int        `json:"id,omitempty"`
	Album   *SavedAlbum `json:"album,omitempty"`
	Error   *string     `json:"error,omitempty"`
}

type SaveMovieInput struct {
	Title    string  `json:"title"`
	Director *string `json:"director,omitempty"`
	Year     *int    `json:"year,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type SaveMovieResponse struct {
	Success bool        `json:"success"`
	ID      *int        `json:"id,omitempty"`
	Movie   *SavedMovie `json:"movie,omitempty"`
	Error   *string     `json:"error,omitempty"`
}

type SavedAlbum struct {
	ID       int     `json:"id"`
	Artist   string  `json:"artist"`
	Album    string  `json:"album"`
	Year     *int    `json:"year,omitempty"`
	Label    *string `json:"label,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type SavedMovie struct {
	ID       int     `json:"id"`
	Title    string  `json:"title"`
	Director *string `json:"director,omitempty"`
	Year     *int    `json:"year,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type TrackData struct {
	Title           string `json:"title"`
	TrackNumber     *int   `json:"trackNumber,omitempty"`
	DurationSeconds *int   `json:"durationSeconds,omitempty"`
}
