// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Album struct {
	ID            string   `json:"id"`
	Artist        string   `json:"artist"`
	Album         string   `json:"album"`
	Year          *int     `json:"year,omitempty"`
	Label         *string  `json:"label,omitempty"`
	ColorVariants []string `json:"color_variants,omitempty"`
	Genres        []string `json:"genres,omitempty"`
	CoverURL      *string  `json:"coverUrl,omitempty"`
	Size          *int     `json:"size,omitempty"`
	CreatedAt     *string  `json:"createdAt,omitempty"`
	UpdatedAt     *string  `json:"updatedAt,omitempty"`
}

type AlbumConnection struct {
	Items    []*Album  `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type AlbumData struct {
	Artist   *string      `json:"artist,omitempty"`
	Album    *string      `json:"album,omitempty"`
	Year     *int         `json:"year,omitempty"`
	Label    *string      `json:"label,omitempty"`
	Genres   []string     `json:"genres,omitempty"`
	CoverURL *string      `json:"coverUrl,omitempty"`
	Tracks   []*TrackData `json:"tracks,omitempty"`
	Source   string       `json:"source"`
}

type AppVersionConfig struct {
	MinimumIOSVersion string `json:"minimumIOSVersion"`
	UpdateMessage     string `json:"updateMessage"`
	ForceUpdate       bool   `json:"forceUpdate"`
	StoreURL          string `json:"storeURL"`
}

type DeleteResponse struct {
	Success bool    `json:"success"`
	Error   *string `json:"error,omitempty"`
}

type Health struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Uptime  int    `json:"uptime"`
}

type ImageUploadURL struct {
	UploadURL string `json:"uploadUrl"`
	ImageURL  string `json:"imageUrl"`
}

type Movie struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Director  *string `json:"director,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	CoverURL  *string `json:"coverUrl,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type MovieConnection struct {
	Items    []*Movie  `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type MovieData struct {
	Title     string  `json:"title"`
	Director  *string `json:"director,omitempty"`
	Year      *int    `json:"year,omitempty"`
	Genre     *string `json:"genre,omitempty"`
	PosterURL *string `json:"posterUrl,omitempty"`
	Plot      *string `json:"plot,omitempty"`
	Source    string  `json:"source"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
	TotalCount  int  `json:"totalCount"`
}

type PaginationInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

type Query struct {
}

type RequestLoginCodeResponse struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Error   *string `json:"error,omitempty"`
}

type SaveAlbumInput struct {
	Artist        string   `json:"artist"`
	Album         string   `json:"album"`
	Year          *int     `json:"year,omitempty"`
	Label         *string  `json:"label,omitempty"`
	ColorVariants []string `json:"color_variants,omitempty"`
	Genres        []string `json:"genres,omitempty"`
	CoverURL      *string  `json:"coverUrl,omitempty"`
	Size          *int     `json:"size,omitempty"`
}

type SaveAlbumResponse struct {
	Success bool        `json:"success"`
	ID      *int        `json:"id,omitempty"`
	Album   *SavedAlbum `json:"album,omitempty"`
	Error   *string     `json:"error,omitempty"`
}

type SaveMovieInput struct {
	Title    string  `json:"title"`
	Director *string `json:"director,omitempty"`
	Year     *int    `json:"year,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type SaveMovieResponse struct {
	Success bool        `json:"success"`
	ID      *int        `json:"id,omitempty"`
	Movie   *SavedMovie `json:"movie,omitempty"`
	Error   *string     `json:"error,omitempty"`
}

type SavedAlbum struct {
	ID            int      `json:"id"`
	Artist        string   `json:"artist"`
	Album         string   `json:"album"`
	Year          *int     `json:"year,omitempty"`
	Label         *string  `json:"label,omitempty"`
	ColorVariants []string `json:"color_variants,omitempty"`
	Genres        []string `json:"genres,omitempty"`
	CoverURL      *string  `json:"coverUrl,omitempty"`
	Size          *int     `json:"size,omitempty"`
}

type SavedMovie struct {
	ID       int     `json:"id"`
	Title    string  `json:"title"`
	Director *string `json:"director,omitempty"`
	Year     *int    `json:"year,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type SortInput struct {
	Field SortField `json:"field"`
	Order SortOrder `json:"order"`
}

type TrackData struct {
	Title           string `json:"title"`
	TrackNumber     *int   `json:"trackNumber,omitempty"`
	DurationSeconds *int   `json:"durationSeconds,omitempty"`
}

type UpdateAlbumInput struct {
	Artist        *string  `json:"artist,omitempty"`
	Album         *string  `json:"album,omitempty"`
	Year          *int     `json:"year,omitempty"`
	Label         *string  `json:"label,omitempty"`
	ColorVariants []string `json:"color_variants,omitempty"`
	Genres        []string `json:"genres,omitempty"`
	CoverURL      *string  `json:"coverUrl,omitempty"`
	Size          *int     `json:"size,omitempty"`
}

type UpdateAlbumResponse struct {
	Success bool    `json:"success"`
	Album   *Album  `json:"album,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type UpdateMovieInput struct {
	Title    *string `json:"title,omitempty"`
	Director *string `json:"director,omitempty"`
	Year     *int    `json:"year,omitempty"`
	Genre    *string `json:"genre,omitempty"`
	CoverURL *string `json:"coverUrl,omitempty"`
}

type UpdateMovieResponse struct {
	Success bool    `json:"success"`
	Movie   *Movie  `json:"movie,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type User struct {
	ID        string   `json:"id"`
	Email     string   `json:"email"`
	CreatedAt string   `json:"createdAt"`
	UpdatedAt string   `json:"updatedAt"`
	Movies    []*Movie `json:"movies"`
	Albums    []*Album `json:"albums"`
}

type VerifyLoginCodeResponse struct {
	Success bool    `json:"success"`
	Token   *string `json:"token,omitempty"`
	User    *User   `json:"user,omitempty"`
	Error   *string `json:"error,omitempty"`
}

type SortField string

const (
	SortFieldCreatedAt SortField = "CREATED_AT"
	SortFieldTitle     SortField = "TITLE"
	SortFieldArtist    SortField = "ARTIST"
	SortFieldYear      SortField = "YEAR"
)

var AllSortField = []SortField{
	SortFieldCreatedAt,
	SortFieldTitle,
	SortFieldArtist,
	SortFieldYear,
}

func (e SortField) IsValid() bool {
	switch e {
	case SortFieldCreatedAt, SortFieldTitle, SortFieldArtist, SortFieldYear:
		return true
	}
	return false
}

func (e SortField) String() string {
	return string(e)
}

func (e *SortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortField", str)
	}
	return nil
}

func (e SortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
